### ISSUE TITLE
tmc-specified record fields may be invalid for record type

### ISSUE THREAD

**Issue by klauer** [slaclab/pytmc#39]
Pragma example:
```yaml
pv: WV_ARRAY
type: waveform
field: DTYP stream
field: NELM 5
field: SCAN 1 second
field: TVL DOUBLE
```

Generated record:
```c
record(ai,"TEST:MAIN:WV_ARRAY"){
  field(TVL, DOUBLE)
  field(PINI, "1")
  field(TSE, -2)
  field(DTYP, "asynInt16ArrayOut")
  field(INP, "@asyn($(PORT),0,1)ADSPORT=851/MAIN.dtype_samples_int_array=")
  field(SCAN, "Passive")
  field(PREC, "3")
  field(FTVL, "SHORT")
  field(NELM, 5)
}
```

DB linter:
```
[DBDLINT] generic_w_pragmas180921.tmc.db line 212 bad-field: recordtype 'waveform' has not field 'TVL'
[DBDLINT] generic_w_pragmas180921.tmc.db line 224 bad-field: recordtype 'waveform' has not field 'TVL'
```
